// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/jmoiron/sqlx"
	"suzushin54/event-sourcing-with-go/app/controller"
	"suzushin54/event-sourcing-with-go/app/infrastructure"
	"suzushin54/event-sourcing-with-go/app/infrastructure/http"
	"suzushin54/event-sourcing-with-go/app/infrastructure/repository_impl"
	"suzushin54/event-sourcing-with-go/app/usecase"
	"suzushin54/event-sourcing-with-go/pkg"
)

// Injectors from injector.go:

func InitServer(db *sqlx.DB, snowflake pkg.SnowflakeNode) *http.Server {
	orderRepositoryV1 := repository_impl.NewOrderRepositoryV1(db)
	orderUseCaseV1 := usecase.NewOrderUseCaseV1(db, orderRepositoryV1, snowflake)
	eventStore := infrastructure.NewMySqlEventStore(db)
	orderRepositoryV2 := repository_impl.NewOrderRepositoryV2(eventStore)
	orderUseCaseV2 := usecase.NewOrderUseCaseV2(orderRepositoryV2, snowflake)
	orderController := controller.NewOrderController(orderUseCaseV1, orderUseCaseV2)
	handler := http.NewMux(orderController)
	server := http.NewServer(handler)
	return server
}
